In [1]:
from __future__ import print_function
import torch
x=torch.Tensor(5,3)
print(x)


tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [2]:
x=torch.rand(5,3)
print(x)

tensor([[0.7784, 0.3387, 0.9722],
        [0.2239, 0.9923, 0.6084],
        [0.0016, 0.8553, 0.5410],
        [0.0552, 0.9568, 0.4342],
        [0.5565, 0.8420, 0.3293]])


In [4]:
print(x.size())

torch.Size([5, 3])


In [5]:
y=torch.rand(5,3)
print(x+y)

tensor([[1.4989, 0.4921, 1.3679],
        [1.0937, 1.5218, 1.0280],
        [0.7001, 1.1349, 0.8783],
        [0.1192, 1.8180, 0.5205],
        [0.9565, 1.0799, 0.7447]])


In [6]:
print(y)

tensor([[0.7205, 0.1534, 0.3956],
        [0.8698, 0.5294, 0.4195],
        [0.6985, 0.2795, 0.3373],
        [0.0640, 0.8612, 0.0863],
        [0.4000, 0.2379, 0.4154]])


In [7]:
print(torch.add(x,y))

tensor([[1.4989, 0.4921, 1.3679],
        [1.0937, 1.5218, 1.0280],
        [0.7001, 1.1349, 0.8783],
        [0.1192, 1.8180, 0.5205],
        [0.9565, 1.0799, 0.7447]])


In [8]:
result=torch.Tensor(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[1.4989, 0.4921, 1.3679],
        [1.0937, 1.5218, 1.0280],
        [0.7001, 1.1349, 0.8783],
        [0.1192, 1.8180, 0.5205],
        [0.9565, 1.0799, 0.7447]])


In [9]:
y.add_(x)
print(y)

tensor([[1.4989, 0.4921, 1.3679],
        [1.0937, 1.5218, 1.0280],
        [0.7001, 1.1349, 0.8783],
        [0.1192, 1.8180, 0.5205],
        [0.9565, 1.0799, 0.7447]])


In [10]:
print(x)

tensor([[0.7784, 0.3387, 0.9722],
        [0.2239, 0.9923, 0.6084],
        [0.0016, 0.8553, 0.5410],
        [0.0552, 0.9568, 0.4342],
        [0.5565, 0.8420, 0.3293]])


In [11]:
print(x[:,1])

tensor([0.3387, 0.9923, 0.8553, 0.9568, 0.8420])


In [12]:
x=torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8)
print(x)

tensor([[-0.7850, -0.3997,  0.9755, -1.6388],
        [ 2.5258,  0.4989, -0.0490,  0.1540],
        [ 1.0424, -1.7261, -0.7720, -1.3923],
        [-0.2428,  0.2571,  0.4507, -0.9779]])


In [13]:
print(y)

tensor([-0.7850, -0.3997,  0.9755, -1.6388,  2.5258,  0.4989, -0.0490,  0.1540,
         1.0424, -1.7261, -0.7720, -1.3923, -0.2428,  0.2571,  0.4507, -0.9779])


In [14]:
print(z)

tensor([[-0.7850, -0.3997,  0.9755, -1.6388,  2.5258,  0.4989, -0.0490,  0.1540],
        [ 1.0424, -1.7261, -0.7720, -1.3923, -0.2428,  0.2571,  0.4507, -0.9779]])


In [15]:
a=torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [17]:
a.add_(1)
print(a)

tensor([2., 2., 2., 2., 2.])


In [18]:
print(b)

[2. 2. 2. 2. 2.]


In [19]:
import numpy as np


In [20]:
a=np.ones(5)
b=torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [21]:
np.add(a,1,out=a)
print(a)

[2. 2. 2. 2. 2.]


In [22]:
print(b)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [24]:
if torch.cuda.is_available():
   x=x.cuda()
   y=y.cuda()
   print(x+y)
    