In [1]:
import torch 
from torch.autograd import Variable
x=Variable(torch.ones(2,2),requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y=x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [5]:
print(y.grad_fn)

In [6]:
z=y*y*3
out=z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [7]:
out.backward()

In [8]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [9]:
x=torch.randn(3)
print(x)

tensor([0.0604, 0.9222, 0.0144])


In [10]:
x=Variable(x,requires_grad=True)
print(x)

tensor([0.0604, 0.9222, 0.0144], requires_grad=True)


In [11]:
y=x+2
print(y)

tensor([2.0604, 2.9222, 2.0144], grad_fn=<AddBackward>)


In [13]:
while y.data.norm() <1000:
    y=y*2
print(y)


tensor([527.4683, 748.0894, 515.6768], grad_fn=<MulBackward>)


In [15]:
print(y.data.norm())

tensor(1050.6107)


In [18]:
gradients=torch.FloatTensor([0.1,1.0,0.0001])
y.backward(gradients)
print(x.grad)

tensor([ 25.6000, 256.0000,   0.0256])


变量是对张量的包装，自定义的变量 grad_fn 为None 

In [ ]:
torch.